-- PostgreSQL Migration Script for Gentlemap

-- 1. Create Tables
CREATE TABLE IF NOT EXISTS categories (
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    parent_id TEXT,
    icon TEXT,
    color TEXT,
    CONSTRAINT fk_parent FOREIGN KEY (parent_id) REFERENCES categories(id)
);

CREATE TABLE IF NOT EXISTS places (
    id SERIAL PRIMARY KEY,
    name TEXT NOT NULL,
    description TEXT,
    category_id TEXT NOT NULL,
    subcategory_id TEXT,
    address TEXT,
    lat DOUBLE PRECISION NOT NULL,
    lng DOUBLE PRECISION NOT NULL,
    price_range INTEGER,
    website TEXT,
    instagram TEXT,
    gentlemap_review TEXT,
    status TEXT DEFAULT 'approved',
    is_featured INTEGER DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_category FOREIGN KEY (category_id) REFERENCES categories(id)
);

CREATE TABLE IF NOT EXISTS reviews (
    id SERIAL PRIMARY KEY,
    place_id INTEGER NOT NULL,
    rating INTEGER NOT NULL,
    comment TEXT,
    user_name TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_place FOREIGN KEY (place_id) REFERENCES places(id)
);

-- 2. Insert Categories
INSERT INTO categories (id, name, parent_id, icon, color) VALUES
('tailleur', 'Tailleur', NULL, 'scissors', '#5A5A40'),
('tailleur_grande', 'Grande Mesure', 'tailleur', NULL, NULL),
('tailleur_sur', 'Sur Mesure', 'tailleur', NULL, NULL),
('tailleur_demi', 'Demi Mesure', 'tailleur', NULL, NULL),
('tailleur_pap', 'Prêt-à-porter', 'tailleur', NULL, NULL),
('costumes_occasion', 'Costumes d''occasion', NULL, 'refresh-cw', '#121212'),
('souliers', 'Beaux Souliers', NULL, 'footprints', '#121212'),
('souliers_sur', 'Sur Mesure', 'souliers', NULL, NULL),
('souliers_demi', 'Demi Mesure', 'souliers', NULL, NULL),
('souliers_pap', 'Prêt-à-porter', 'souliers', NULL, NULL),
('chapeliers', 'Chapeliers et accessoires', NULL, 'shopping-bag', '#121212'),
('antiquaires', 'Antiquaires', NULL, 'lamp', '#121212'),
('librairies', 'Librairies anciennes', NULL, 'book-open', '#121212'),
('artisans', 'Artisans d''art', NULL, 'hammer', '#121212'),
('cafes', 'Cafés historiques', NULL, 'coffee', '#121212'),
('restaurants', 'Restaurants', NULL, 'utensils', '#121212'),
('hotels', 'Hôtels de charme', NULL, 'bed', '#121212')
ON CONFLICT (id) DO NOTHING;

-- 3. Insert Initial Places
INSERT INTO places (name, description, category_id, subcategory_id, address, lat, lng, price_range, website, instagram, gentlemap_review, is_featured) VALUES
('Cifonelli', 'L''un des plus célèbres tailleurs de la Grande Mesure parisienne.', 'tailleur', 'tailleur_grande', '31 Rue Marbeuf, 75008 Paris', 48.8694, 2.3045, 4, 'https://www.cifonelli.com', 'cifonelli_official', 'Une épaule iconique et un savoir-faire inégalé.', 0),
('Scavini', 'Tailleur de renom, célèbre pour son style et son expertise technique.', 'tailleur', 'tailleur_demi', '50 Boulevard de la Tour-Maubourg, 75007 Paris', 48.8592, 2.3118, 3, 'https://www.scavini.fr', 'scavini_tailleur', 'L''élégance parisienne avec une touche de modernité technique.', 1),
('Chez Ammar', 'Friperie de luxe et sélection vintage exceptionnelle.', 'costumes_occasion', NULL, '13 Rue de la Grange Batelière, 75009 Paris', 48.8732, 2.3415, 2, NULL, 'chez_ammar_vintage', 'Une caverne d''Alibaba pour les amateurs de pièces rares.', 1),
('Le Select', 'Café historique de Montparnasse, fréquenté par les plus grands artistes.', 'cafes', NULL, '99 Bd du Montparnasse, 75006 Paris', 48.8425, 2.3289, 2, 'https://www.leselectmontparnasse.fr', 'leselectmontparnasse', 'L''ambiance du Paris littéraire est encore palpable.', 0),
('Berluti', 'Bottier d''exception depuis 1895.', 'souliers', 'souliers_sur', '26 Rue Marbeuf, 75008 Paris', 48.8696, 2.3038, 4, 'https://www.berluti.com', 'berluti', 'Le cuir Venezia est une légende.', 0),
('Aubercy', 'Maison de souliers familiale et indépendante.', 'souliers', 'souliers_sur', '34 Rue Vivienne, 75002 Paris', 48.8692, 2.3401, 4, 'https://www.aubercy.com', 'aubercy', 'Un style unique et une exigence rare.', 0),
('J.M. Weston', 'L''emblème du soulier français.', 'souliers', 'souliers_pap', '114 Av. des Champs-Élysées, 75008 Paris', 48.8721, 2.3005, 3, 'https://www.jmweston.com', 'jmwestonofficial', 'Le Mocassin 180 est un indispensable.', 0),
('Charvet', 'Le plus ancien chemisier du monde.', 'artisans', NULL, '28 Pl. Vendôme, 75001 Paris', 48.8675, 2.3294, 4, 'https://www.charvet.com', NULL, 'Le temple de la soie et du coton.', 0),
('Camps de Luca', 'L''excellence de la coupe parisienne.', 'tailleur', 'tailleur_grande', '16 Rue de la Paix, 75002 Paris', 48.8691, 2.3305, 4, 'https://www.campsdeluca.com', 'campsdeluca', 'Une précision chirurgicale.', 0),
('Maison Bonnet', 'Maître lunetier d''art.', 'artisans', NULL, '5 Rue des Petits Champs, 75001 Paris', 48.8665, 2.3385, 4, 'https://www.maisonbonnet.com', 'maisonbonnet', 'L''écaille de tortue travaillée à la main.', 0),
('Librairie Galignani', 'La plus ancienne librairie anglophone du continent.', 'librairies', NULL, '224 Rue de Rivoli, 75001 Paris', 48.8651, 2.3285, 2, 'https://www.galignani.fr', 'librairiegalignani', 'Un cadre somptueux sous les arcades.', 0),
('Shakespeare and Company', 'Librairie mythique face à Notre-Dame.', 'librairies', NULL, '37 Rue de la Bûcherie, 75005 Paris', 48.8525, 2.3471, 2, 'https://shakespeareandcompany.com', 'shakespeareandcoparis', 'Un labyrinthe de livres chargé d''histoire.', 0),
('Café de Flore', 'Le rendez-vous des existentialistes.', 'cafes', NULL, '172 Bd Saint-Germain, 75006 Paris', 48.8542, 2.3331, 3, 'https://cafedeflore.fr', 'lecafedeflore', 'Plus qu''un café, une institution.', 0),
('Les Deux Magots', 'Concurrent historique du Flore.', 'cafes', NULL, '6 Pl. Saint-Germain des Prés, 75006 Paris', 48.8541, 2.3335, 3, 'https://lesdeuxmagots.fr', 'lesdeuxmagots', 'Une terrasse iconique.', 0),
('L''Hôtel', 'Le plus petit hôtel 5 étoiles de Paris.', 'hotels', NULL, '13 Rue des Beaux Arts, 75006 Paris', 48.8558, 2.3345, 4, 'https://www.l-hotel.com', 'lhotel_paris', 'Dernière demeure d''Oscar Wilde.', 0),
('Le Grand Véfour', 'Restaurant historique du Palais Royal.', 'restaurants', NULL, '17 Rue de Beaujolais, 75001 Paris', 48.8665, 2.3395, 4, 'https://www.grand-vefour.com', 'legrandvefour', 'Un décor Directoire époustouflant.', 0),
('Brasserie Lipp', 'Temple de la cuisine traditionnelle.', 'restaurants', NULL, '151 Bd Saint-Germain, 75006 Paris', 48.8541, 2.3328, 3, 'https://www.brasserielipp.fr', 'brasserielipp', 'Le cervelas rémoulade est un classique.', 0),
('Antiquités Brocante du Village Saint-Paul', 'Un village d''antiquaires caché dans le Marais.', 'antiquaires', NULL, 'Rue Saint-Paul, 75004 Paris', 48.8535, 2.3615, 2, NULL, NULL, 'Un havre de paix pour chineurs.', 0),
('Marché aux Puces de Saint-Ouen', 'Le plus grand marché d''antiquités au monde.', 'antiquaires', NULL, 'Av. de la Porte de Clignancourt, 93400 Saint-Ouen', 48.9015, 2.3425, 2, 'https://www.pucesdesaintouen.com', 'pucesdesaintouen', 'Une exploration infinie.', 0),
('La Belle Hortense', 'Librairie-bar à vin dans le Marais.', 'librairies', NULL, '31 Rue Vieille du Temple, 75004 Paris', 48.8575, 2.3575, 2, NULL, 'labellehortense', 'Lire en buvant un bon cru.', 0),
('Le Comptoir de l''Avenir', 'Friperie vintage sélectionnée.', 'costumes_occasion', NULL, '6 Rue de l''Avenir, 75020 Paris', 48.8755, 2.3955, 1, NULL, NULL, 'Des pépites à prix doux.', 0),
('Maison Fabre', 'Gantier d''art depuis 1924.', 'artisans', NULL, 'Jardin du Palais Royal, 75001 Paris', 48.8655, 2.3375, 3, 'https://www.maisonfabre.com', 'maisonfabre', 'La finesse du cuir de Millau.', 0),
('Chapellerie Motsch', 'Intégrée à Hermès, excellence du chapeau.', 'chapeliers', NULL, '42 Av. George V, 75008 Paris', 48.8705, 2.3015, 4, NULL, NULL, 'Le summum du couvre-chef.', 0),
('Lock & Co. Hatters (Paris Agent)', 'Représentant de la célèbre maison londonienne.', 'chapeliers', NULL, 'Paris', 48.8566, 2.3522, 4, 'https://www.lockhatters.com', NULL, 'Le summum du couvre-chef britannique à Paris.', 0),
('Le Bal des Ardents', 'Librairie à la façade magnifique.', 'librairies', NULL, '17 Rue Neuve, 69001 Lyon', 45.7655, 4.8355, 2, 'https://www.lebaldesardents.com', 'lebaldesardents', 'Une arche de livres unique.', 0),
('Café des Fédérations', 'Bouchon lyonnais authentique.', 'restaurants', NULL, '8 Rue Major Martin, 69001 Lyon', 45.7675, 4.8325, 2, 'https://www.les-federations-lyon.fr', 'cafedesfederations', 'La tradition lyonnaise pure.', 0),
('Cour des Loges', 'Hôtel Renaissance au coeur du Vieux Lyon.', 'hotels', NULL, '6 Rue du Boeuf, 69005 Lyon', 45.7635, 4.8275, 4, 'https://www.courdesloges.com', 'courdesloges', 'Un voyage dans le temps.', 0),
('Antiquités de la Cité', 'Quartier des antiquaires lyonnais.', 'antiquaires', NULL, 'Rue Auguste Comte, 69002 Lyon', 45.7555, 4.8315, 3, NULL, NULL, 'Le quartier chic de la chine.', 0),
('Atelier de Soierie', 'Impression sur soie traditionnelle.', 'artisans', NULL, '33 Rue Romarin, 69001 Lyon', 45.7685, 4.8345, 3, 'https://www.atelierdesoierie.com', NULL, 'L''héritage des Canuts.', 0),
('Librairie Mollat', 'La plus grande librairie indépendante de France.', 'librairies', NULL, '15 Rue Vital Carles, 33000 Bordeaux', 44.8405, -0.5785, 2, 'https://www.mollat.com', 'librairie_mollat', 'Un temple de la culture.', 0),
('Le Grand Hôtel Bordeaux', 'L''élégance classique face au Grand Théâtre.', 'hotels', NULL, '2-5 Pl. de la Comédie, 33000 Bordeaux', 44.8425, -0.5745, 4, 'https://bordeaux.intercontinental.com', 'intercontinental_bordeaux', 'Le luxe bordelais par excellence.', 0),
('Café de l''Espérance', 'Café de village chic à Bouliac.', 'cafes', NULL, 'Bouliac', 44.8145, -0.5045, 2, NULL, NULL, 'Une vue imprenable sur la Garonne.', 0),
('Antiquités du Passage', 'Brocante et antiquités sélectionnées.', 'antiquaires', NULL, 'Quartier des Chartrons, 33000 Bordeaux', 44.8525, -0.5725, 3, NULL, NULL, 'L''esprit des Chartrons.', 0),
('Maison Empereur', 'La plus ancienne quincaillerie de France.', 'artisans', NULL, '4 Rue des Récolettes, 13001 Marseille', 43.2965, 5.3775, 2, 'https://www.empereur.fr', 'maisonempereur', 'Un inventaire incroyable.', 0),
('Le Petit Nice Passedat', 'Hôtel et restaurant gastronomique face à la mer.', 'hotels', NULL, 'Anse de Maldormé, 13007 Marseille', 43.2825, 5.3515, 4, 'https://www.passedat.fr', 'lepetitnicepassedat', 'La Méditerranée dans l''assiette.', 0),
('Librairie Maupetit', 'Institution culturelle sur la Canebière.', 'librairies', NULL, '142 La Canebière, 13001 Marseille', 43.2985, 5.3845, 2, 'https://www.maupetitforton.fr', NULL, 'Le coeur littéraire de Marseille.', 0),
('Hôtel Negresco', 'Palais mythique de la Promenade des Anglais.', 'hotels', NULL, '37 Promenade des Anglais, 06000 Nice', 43.6945, 7.2575, 4, 'https://www.hotel-negresco-nice.com', 'hotelnegresco', 'Une collection d''art vivante.', 0),
('Le Plongeoir', 'Restaurant sur un rocher en mer.', 'restaurants', NULL, '60 Bd Franck Pilatte, 06300 Nice', 43.6915, 7.2885, 4, 'https://www.leplongeoir.com', 'leplongeoir', 'Une expérience suspendue.', 0),
('Café Christian', 'Pâtisserie et salon de thé raffiné.', 'cafes', NULL, '10 Rue de l''Outre, 67000 Strasbourg', 48.5835, 7.7475, 3, 'https://christian.fr', NULL, 'Le goût de l''Alsace élégante.', 0),
('Meert', 'Pâtisserie et salon de thé historique.', 'cafes', NULL, '27 Rue Esquermoise, 59000 Lille', 50.6375, 3.0615, 3, 'https://www.meert.fr', 'meert_1761', 'Les gaufres préférées du Général de Gaulle.', 0),
('Le Furet du Nord', 'L''une des plus grandes librairies d''Europe.', 'librairies', NULL, '15 Pl. du Général de Gaulle, 59000 Lille', 50.6365, 3.0635, 2, 'https://www.furet.com', 'furetdunord', 'Un phare culturel.', 0),
('Le Bibent', 'Brasserie historique sur la place du Capitole.', 'restaurants', NULL, '5 Pl. du Capitole, 31000 Toulouse', 43.6045, 1.4435, 3, 'https://www.maisonconstant.com/bibent/', NULL, 'Un décor baroque classé.', 0),
('Librairie Ombres Blanches', 'Librairie indépendante de référence.', 'librairies', NULL, '50 Rue Gambetta, 31000 Toulouse', 43.6035, 1.4415, 2, 'https://www.ombres-blanches.fr', 'ombresblanches', 'Un espace de réflexion.', 0),
('Les Deux Garçons', 'Café mythique du Cours Mirabeau.', 'cafes', NULL, '53 Cours Mirabeau, 13100 Aix-en-Provence', 43.5265, 5.4495, 3, NULL, NULL, 'Le rendez-vous de Cézanne et Zola.', 0),
('La Cigale', 'Brasserie Art Nouveau classée.', 'restaurants', NULL, '4 Pl. Graslin, 44000 Nantes', 47.2125, -1.5615, 3, 'https://www.lacigale.com', 'lacigale_nantes', 'Le plus beau décor de brasserie de France.', 0),
('L''Hôtel de Bourgtheroulde', 'Hôtel de luxe dans un monument historique.', 'hotels', NULL, '15 Pl. de la Pucelle, 76000 Rouen', 49.4415, 1.0885, 4, 'https://www.hotelsparouen.com', NULL, 'La Renaissance à l''état pur.', 0),
('Auzou', 'Chocolatier et pâtissier de renom.', 'artisans', NULL, '163 Rue du Gros Horloge, 76000 Rouen', 49.4415, 1.0915, 3, 'https://www.auzou-chocolat.fr', 'auzou_rouen', 'Les larmes de Jeanne d''Arc.', 0),
('Le Grand Cerf', 'Restaurant gastronomique étoilé.', 'restaurants', NULL, 'Montchenot', 49.1645, 3.9945, 4, 'https://www.legrandcerf.fr', NULL, 'La Champagne dans toute sa splendeur.', 0),
('Maison Fossier', 'Biscuiterie historique.', 'artisans', NULL, '25 Cr Jean-Baptiste Langlet, 51100 Reims', 49.2555, 4.0315, 2, 'https://www.fossier.fr', 'maisonfossier', 'Le véritable Biscuit Rose de Reims.', 0),
('Hôtel du Palais', 'Ancienne résidence impériale.', 'hotels', NULL, '1 Av. de l''Impératrice, 64200 Biarritz', 43.4885, -1.5545, 4, 'https://www.hotel-du-palais.com', 'hoteldupalais', 'Le luxe face à l''Océan.', 0),
('Miremont', 'Pâtisserie et salon de thé historique.', 'cafes', NULL, '1 Pl. Clemenceau, 64200 Biarritz', 43.4835, -1.5595, 3, 'https://www.miremont-biarritz.fr', 'miremont_biarritz', 'Une vue royale sur la Grande Plage.', 0),
('Hôtel Le Normandy', 'L''élégance anglo-normande.', 'hotels', NULL, '38 Rue Jean Mermoz, 14800 Deauville', 49.3615, 0.0745, 4, 'https://www.hotelsbarriere.com', 'lenormandydeauville', 'Le charme des planches.', 0),
('La Mirande', 'Hôtel particulier face au Palais des Papes.', 'hotels', NULL, '4 Pl. de l''Amirande, 84000 Avignon', 43.9505, 4.8075, 4, 'https://www.la-mirande.fr', 'la_mirande', 'Un raffinement hors du temps.', 0),
('L''Hôtel Particulier', 'Hôtel de charme dans le centre historique.', 'hotels', NULL, '4 Rue de la Monnaie, 13200 Arles', 43.6795, 4.6245, 4, 'https://www.hotel-particulier.com', 'lhotelparticulierarles', 'L''esprit de la Provence élégante.', 0),
('Actes Sud', 'Librairie et maison d''édition.', 'librairies', NULL, 'Pl. Nina Berberova, 13200 Arles', 43.6765, 4.6215, 2, 'https://www.actes-sud.fr', 'actessud', 'Un lieu de culture foisonnant.', 0),
('Le Jardin des Sens', 'Restaurant gastronomique des frères Pourcel.', 'restaurants', NULL, 'Montpellier', 43.6105, 3.8765, 4, 'https://www.terminal-pourcel.com', NULL, 'L''innovation culinaire du Sud.', 0),
('Le Coq-Gadby', 'Hôtel et restaurant traditionnel.', 'hotels', NULL, '156 Rue d''Antrain, 35700 Rennes', 48.1225, -1.6745, 3, 'https://www.lecoq-gadby.com', NULL, 'L''hospitalité bretonne.', 0),
('Maison Mulot & Petitjean', 'Fabrique historique de pain d''épices.', 'artisans', NULL, '13 Pl. Bossuet, 21000 Dijon', 47.3215, 5.0375, 2, 'https://www.mulotpetitjean.fr', 'mulotpetitjean', 'Le goût authentique de Dijon.', 0),
('Le Grand Hôtel Grenoble', 'Élégance au centre-ville.', 'hotels', NULL, '5 Rue de la République, 38000 Grenoble', 45.1915, 5.7295, 3, 'https://www.grand-hotel-grenoble.com', NULL, 'Le charme alpin.', 0),
('Hôtel de l''Univers', 'Hôtel historique de prestige.', 'hotels', NULL, '5 Bd Heurteloup, 37000 Tours', 47.3915, 0.6915, 3, 'https://www.hotel-univers.fr', NULL, 'Le luxe en Touraine.', 0),
('Le Quernon d''Ardoise', 'Chocolaterie La Petite Marquise.', 'artisans', NULL, '22 Rue des Lices, 49100 Angers', 47.4695, -0.5515, 2, 'https://www.quernon.fr', NULL, 'Le bleu de l''Anjou.', 0),
('L''Hôtel Radio', 'Hôtel et restaurant gastronomique.', 'hotels', NULL, 'Chamalières', 45.7745, 3.0545, 3, 'https://www.hotel-radio.fr', NULL, 'Une vue sur les volcans.', 0),
('Bernardaud', 'Manufacture de porcelaine.', 'artisans', NULL, '27 Av. Albert Thomas, 87000 Limoges', 45.8365, 1.2475, 4, 'https://www.bernardaud.com', 'bernardaud', 'L''excellence de la porcelaine.', 0),
('L''Auberge du Père Bise', 'Hôtel et restaurant au bord du lac.', 'hotels', NULL, 'Talloires', 45.8415, 6.2135, 4, 'https://www.perebise.com', 'aubergeduperebise', 'Un paradis lacustre.', 0),
('Le Hameau Albert 1er', 'Hôtel de luxe face au Mont-Blanc.', 'hotels', NULL, '38 Route du Bouchet, 74400 Chamonix', 45.9255, 6.8745, 4, 'https://www.hameaualbert.fr', 'hameaualbert1er', 'La montagne raffinée.', 0),
('Hôtel Byblos', 'Le temple des nuits tropéziennes.', 'hotels', NULL, '20 Av. Paul Signac, 83990 Saint-Tropez', 43.2715, 6.6425, 4, 'https://www.byblos.com', 'hotelbyblossttropez', 'La légende de Saint-Tropez.', 0),
('Sénéquier', 'Café iconique sur le port.', 'cafes', NULL, 'Quai Jean Jaurès, 83990 Saint-Tropez', 43.2725, 6.6395, 4, 'https://www.senequier.com', 'senequiersttropez', 'Le rouge emblématique.', 0),
('Hôtel Martinez', 'L''esprit Art Déco sur la Croisette.', 'hotels', NULL, '73 Bd de la Croisette, 06400 Cannes', 43.5485, 7.0315, 4, 'https://www.hotel-martinez.com', 'hotelmartinez', 'Le glamour du Festival.', 0),
('Airelles Château de Versailles', 'Hôtel dans l''enceinte du Château.', 'hotels', NULL, '1 Rue de l''Indépendance Américaine, 78000 Versailles', 48.8035, 2.1205, 4, 'https://airelles.com', 'airelleschateaudeversailles', 'Vivre comme un roi.', 0),
('L''Aigle Noir', 'Hôtel historique face au château.', 'hotels', NULL, '27 Pl. Napoléon Bonaparte, 77300 Fontainebleau', 48.4035, 2.6995, 3, 'https://www.aiglenoirhotel.com', NULL, 'L''élégance impériale.', 0),
('Hôtel Fleur de Loire', 'Hôtel et restaurant de Christophe Hay.', 'hotels', NULL, '26 Quai Villebois Mareuil, 41000 Blois', 47.5855, 1.3385, 4, 'https://fleurdeloire.com', 'fleurdeloire', 'La gastronomie de Loire.', 0),
('Hôtel de la Cité', 'Hôtel au coeur de la cité médiévale.', 'hotels', NULL, 'Pl. de l''Église, 11000 Carcassonne', 43.2065, 2.3645, 4, 'https://www.hoteldelacite.com', 'hoteldelacite', 'Une forteresse de luxe.', 0),
('Chocolat Cazenave', 'Chocolatier historique sous les arcades.', 'artisans', NULL, '19 Rue Port Neuf, 64100 Bayonne', 43.4915, -1.4755, 3, 'https://www.chocolats-cazenave.fr', NULL, 'Le chocolat mousseux traditionnel.', 0),
('Brasserie L''Excelsior', 'Chef-d''oeuvre de l''Art Nouveau.', 'restaurants', NULL, '50 Rue Henri Poincaré, 54000 Nancy', 48.6915, 6.1755, 3, 'https://www.brasserie-excelsior-nancy.fr', 'brasserie_excelsior_nancy', 'L''esprit de l''École de Nancy.', 0),
('La Mère Poulard', 'Auberge historique célèbre pour son omelette.', 'restaurants', NULL, 'Grande Rue, 50170 Le Mont-Saint-Michel', 48.6355, -1.5105, 4, 'https://lamerepoulard.com', 'lamerepoulard', 'Une tradition séculaire.', 0);
